package com.globant.videoplayerproject.utils

const val API_KEY = "xzpd1f4527fu8fct7p7own0pgi35v5"
const val HEADER_API_KEY = "Client-ID: $API_KEY"
const val HEADER_AUTHORIZATION = "Authorization"
const val QUERY_FIRST_RESULTS = "first"
const val QUERY_USER_ID = "user_id"
const val QUERY_GAME_ID = "game_id"
const val QUERY_CLIENT_ID = "client_id"
const val QUERY_CLIENT_SECRET = "client_secret"
const val QUERY_GRANT_TYPE = "grant_type"
const val ACTUAL_DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss'Z'"
const val REQUIRED_DATE_FORMAT = "HH:mm • EEE, M/d"
const val ACTUAL_WIDTH_HEIGHT_IMAGE = "{width}x{height}"
const val REQUIRED_WIDTH_HEIGHT = "150x170"
const val ACTUAL_WIDTH_HEIGHT_VIDEOS = "%{width}x%{height}"
const val ACTUAL_AUTHENTICATION_TYPE = "b"
const val CORRECT_AUTHENTICATION_TYPE = "B"
